apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: elastic-stack
type: Opaque
stringData:
  elastic_password: "changeme-elastic-password"
  apm_secret_token: "changeme-apm-secret-token"
  kibana_password: "changeme-kibana-password"
