apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: OTEL_SERVICE_NAME
              value: cartservice
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-agent:4317
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.version=1.0.0,deployment.environment=assessment"
