apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-k8s-audit-config
  namespace: elastic-stack
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: k8s-audit
        paths:
          - /var/log/kubernetes/audit.log
        parsers:
          - ndjson:
              add_error_key: true
    processors:
      - add_kubernetes_metadata: {}
    output.elasticsearch:
      hosts: ["http://elasticsearch.elastic-stack:9200"]
      username: "elastic"
      password: "${ELASTIC_PASSWORD}"
    setup.kibana:
      host: "http://kibana.elastic-stack:5601"
