apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: OTEL_SERVICE_NAME
              value: paymentservice
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-agent:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.version=1.0.0,deployment.environment=assessment"
