apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: ENABLE_TRACING
              value: "1"
            - name: COLLECTOR_SERVICE_ADDR
              value: otel-agent:4317
            - name: OTEL_SERVICE_NAME
              value: paymentservice
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.version=1.0.0,deployment.environment=assessment"
